### ISSUE TITLE
Customize colors ?

### ISSUE THREAD

**Issue by imacnu** [adrian5/oceanic-next-vim#6]
It is possible to customize some colours, for example for stratify or coc-explorer ? Thanks

**Comment by adrian5** [comment]
### vim-startify

I've already explicitly styled [vim-startify](https://github.com/mhinz/vim-startify) (which I assume you mean) and am satisfied with it. Anything in particular you'd want to see changed?

If you want to override some yourself, you can look at `:h startify-colors` and do e.g.:

```viml
colorscheme oceanicnext
…
hi! link StartifyNumber OcRed
```

In place of `OcRed` can use one of the colors [here](https://github.com/adrian5/oceanic-next-vim/blob/master/colors/oceanicnext.vim#L151-L176).

### coc-explorer

Can you upload a screeenshot of how it looks right now? Many plugins pick up sane defaults from vim, but maybe this one doesn't.

**Comment by adrian5** [comment]
Note to self: coc-explorer [hl-Groups](https://github.com/weirongxu/coc-explorer/wiki/Highlight)

**Comment by imacnu** [comment]
Thaaaaanks, I have been able to change the colours of coc explorer and startify with your instructions. Thank you so much. Could I change any colorscheme colour, can I edit oceanicnext.vim ?

**Comment by adrian5** [comment]
Ok, nice. I'll leave this topic for now. If I find the time, I'll have a look at coc-explorer styling and how it can be improved for this theme.

Regarding `oceanicnext.vim` editing, you can certainly do that, sure. But it won't work if you use a plugin-manager, since any changes would be overwritten on the next update. If you install the theme manually, then nothing prevents you from customizing colors as you wish, even the [base palette](https://github.com/adrian5/oceanic-next-vim/blob/3ef258c7884b4f8525622d018aa0663f87d004d7/colors/oceanicnext.vim#L113-L147).

**Comment by imacnu** [comment]
O, I have installed with Plug !!. Thank you so much, greeeat support !!
