### ISSUE TITLE
Can't seem to enable this plugin without textwidth defaulting to 78

### ISSUE THREAD

**Issue by wnim** [adrian5/oceanic-next-vim#9]
I installed it using vim-plug and even since I get textwidth = 78 even though my vimrc sets it to 0.
when I comment out this plugin from my vimrc the textwidth returns to 0.

**Comment by adrian5** [comment]
Hello Nimi. The colorscheme file itself [sets a few properties](https://github.com/adrian5/oceanic-next-vim/blob/master/colors/oceanicnext.vim#L901) so that contributors get the right line length, indentation etc. when making changes. To my knowledge this shouldn't affect your global vim settings, and it doesn't do so on my system.

Are you on vim or nvim?

**Comment by wnim** [comment]
I'm on vim

**Comment by adrian5** [comment]
What's the output of `:verbose set tw`?

**Comment by wnim** [comment]
textwidth=78
        Last set from /usr/local/share/vim/vim82/ftplugin/vim.vim line 65

I'm now realizing that it was not commenting of the oceanic-next-vim that changed the text width, but rather opening a different filetype. 🙏

At least I learned about verbose command  :)

**Comment by adrian5** [comment]
Happens to me too, software is complicated. I'll close this issue then.

As an aside, I recommend giving [nvim](https://github.com/neovim/neovim/) a try if you can. In my experience it only has upsides.
